package it.polimi.ingsw.ps46.server;

public enum ActionSpaceName {
	GREEN_TOWER_FLOOR_1, GREEN_TOWER_FLOOR_2, GREEN_TOWER_FLOOR_3, GREEN_TOWER_FLOOR_4,
	BLUE_TOWER_FLOOR_1, BLUE_TOWER_FLOOR_2, BLUE_TOWER_FLOOR_3, BLUE_TOWER_FLOOR_4,
	YELLOW_TOWER_FLOOR_1, YELLOW_TOWER_FLOOR_2, YELLOW_TOWER_FLOOR_3, YELLOW_TOWER_FLOOR_4,
	PURPLE_TOWER_FLOOR_1, PURPLE_TOWER_FLOOR_2, PURPLE_TOWER_FLOOR_3, PURPLE_TOWER_FLOOR_4,
	PRODUCTION_SPACE_1, PRODUCTION_SPACE_2, HARVEST_SPACE_1, HARVEST_SPACE_2, COUNSIL_SPACE
}
