package it.polimi.ingsw.ps46.server;

public enum GameState {
	SETUP_GAME, SETUP_PLAYERS_USERNAME, SETUP_INITIAL_ORDER, SETUP_PLAYERS_COLOR, SETUP_INITIAL_RESOURCES, SETUP_ROUND, GET_PLAYER_ACTION, ACTION_NOT_VALID, 
	COUNCIL_ACTION, COUNCIL_PRIVILEGE, SETUP_BONUS_TILES, VATICAN_REPORT, MISSING_TURN, EXTRA_MOVE, ACTIVATION_LEADER_CARDS, DISCARD_LEADER_CARDS
}
