package it.polimi.ingsw.ps46.server;

public enum InputType {
	PLAYER_USERNAME, PLAYER_COLOR, PLAYER_ACTION, FAMILY_MEMBER_CHOICE, SERVANTS_USED, EFFECT_CHOICE, COUNCIL_PRIVILEGE_CHOICE, BONUS_TILE_CHOICE, VATICAN_SUPPORT_CHOICE, FAMILY_MEMBER_DICE_BONUS_CHOICE, ACTIVATION_LEADER_CARDS_CHOICE, DISCARD_LEADER_CARDS_CHOICE
}
