package it.polimi.ingsw.ps46.server;

public enum NewStateMessage {
	START_GAME, GAME_STARTED, CHANGED_CURRENT_PLAYER, SET_INITIAL_ORDER, UPDATE_ROUND_INFO,THROWN_DICE, ACTION_SENT,
	UPDATE_CURRENT_PLAYER_POSITION, UPDATE_CURRENT_PLAYER_STATE, UPDATE_DICE_VALUE, UPDATE_CARDS_ON_BOARD, NOT_VALID_MOVE, WELCOME_MESSAGE, SETUP_GAME;
}
