package it.polimi.ingsw.ps46.server;

public enum NewStateMessage {
	START_GAME, GAME_STARTED, ADVANCED_GAME_MODE, CHANGED_CURRENT_PLAYER, SET_INITIAL_ORDER, UPDATE_ROUND_INFO, ACTION_SENT, SET_NEXT_TURN_ORDER,
	EXCHANGE_RESOURCES_CHOICE, UPDATE_PHASE_INFO, UPDATE_FINAL_SCORES, CARD_COST_CHOICE, EXTRA_MOVE;
}
