package it.polimi.ingsw.ps46.server;

public enum NewStateMessage {
	START_GAME, GAME_STARTED, ADVANCED_GAME_MODE, CHANGED_CURRENT_PLAYER, SET_INITIAL_ORDER, UPDATE_ROUND_INFO,THROWN_DICE, ACTION_SENT, SET_NEXT_TURN_ORDER;
}
